#!/usr/bin/env python
# coding=utf8

import fontforge
from argparse import ArgumentParser

# Setup and parse the comand-line arguments
parser = ArgumentParser()
parser.add_argument("--input", help="input file name")
parser.add_argument("--output", help="output file name")
parser.add_argument("--name", help="font name")
parser.add_argument("--version", help="(optional) text to add to the existing version")
args = parser.parse_args()

# Open the file
font=fontforge.open(args.input)

# Rename the file
font.fontname="{}-Regular".format(args.name).replace(" ", "")
font.familyname=args.name
font.fullname=args.name
font.appendSFNTName("English (US)", "Preferred Family", args.name)
font.appendSFNTName("English (US)", "Compatible Full", args.name)
font.appendSFNTName("English (US)", "UniqueID", "{} Regular".format(args.name))
font.appendSFNTName("English (US)", "Trademark", "")

# The grave accent type is somehow not correctly detected;
# we want it to be an ordinary character
font["grave"].glyphclass="baseglyph"

# Mix our version information in
font.appendSFNTName("English (US)", "Version", args.version)
font.version = args.version

# Save
font.generate(args.output)
