name: Generate Fonts

# spell-checker:ignore Cascadia Cascodia Delugia PowerLine chmod configParser dbin fontForge progressBars softprops xargs mkdir

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create all needed build/work directories
      run: mkdir -p 'build'
    - name: Download Cascadia font
      run: curl -L https://github.com/microsoft/cascadia-code/releases/download/v1910.04/Cascadia.ttf  --output 'build/Cascadia.ttf'
    - name: Install FontForge
      run: |
        sudo add-apt-repository ppa:fontforge/fontforge -y -u ;
        sudo apt-get install fontforge -y ;
    - name: Download Font Patcher
      run: curl -L https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/font-patcher --output 'build/font-patcher'
    - name: Patch Font Patcher for Ligature Glyphs
      run: patch -u 'build/font-patcher' < dbin/font-patcher.patch
    - name: Download source fonts
      run: |
        cd build
        chmod +x ../dbin/download-source-fonts.sh
        ../dbin/download-source-fonts.sh
    - name: Install PIP
      run: sudo apt install python-pip -y
    - name: Install configparser
      run: pip install configparser
    - name: Build Powerline
      run: |
        cd 'build'
        fontforge -script font-patcher --powerline --no-progressbars --mono Cascadia.ttf
        git describe --always | xargs fontforge ../dbin/rename-font --input "Cascadia Code Nerd Font Mono.ttf" \
                                                            --output "Cascodia NF Powerline.ttf" \
                                                            --name "Cascodia Nerd Font" \
                                                            --version
    - name: Build Complete
      run: |
        cd 'build'
        fontforge -script font-patcher -c --no-progressbars --mono Cascadia.ttf
        git describe --always | xargs fontforge ../dbin/rename-font --input "Cascadia Code Nerd Font Complete Mono.ttf" \
                                                            --output "Cascodia NF.ttf" \
                                                            --name "Cascodia Nerd Font" \
                                                            --version
    - uses: actions/upload-artifact@master
      with:
        name: Cascodia Nerd Font Powerline
        path: "build/Cascodia NF Powerline.ttf"
    - uses: actions/upload-artifact@master
      with:
        name: Cascodia Nerd Font Complete
        path: "build/Cascodia NF.ttf"
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/Cascodia NF Powerline.ttf
          build/Cascodia NF.ttf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
